services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5544:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prefect:
    image: prefecthq/prefect:3-python3.12
    network_mode: host
    command: ["prefect", "server", "start"]
    healthcheck:
      test: python -c "import requests; requests.get('http://localhost:4200/api/health').raise_for_status()"
      start_period: 10s
      start_interval: 1s
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: