services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5544:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prefect:
    image: prefecthq/prefect:3-python3.12
    ports:
        - "4200:4200"

volumes:
  postgres_data: